name: Back End Deployment
on :
  push:
     branches:
        - main

jobs:
  # Unit Test
  Unit-Test:
    runs-on: ubuntu-latest
    steps: 
        - name: checkout code
          uses: actions/checkout@v5

        - name: Install Dependencies
          run: npm i

        - name: run unit Test
          run: npm run test


  # Build And Push
  runs-on: ubuntu-latest
  needs: Unit-Test
  steps:
    - name: checkout code
      uses: actions/checkout@v5
    
    - name: Build Docker Image
      run: docker build -t dhouhalamine/api-session14 .

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: List Images
      run: docker images

  # Deployment 


      
