name: Back End Deployment
on :
  push:
     branches:
        - main

jobs:
  # Unit Test
  Unit Test:
    runs-on: ubuntu-latest
    steps: 
        - name: checkout code
          uses: actions/checkout@v5

        - name: Install Dependencies
          uses: npm i

        - name: run unit Test
          run: npm run test


  # Build And Push

  # Deployment 


      
